### ISSUE TITLE
Bringing back Authserver

### ISSUE THREAD

**Issue by miirak** [The-Cataclysm-Preservation-Project/TrinityCore#135]
**Description:**

Okay so I really wanted to open this issue, because we are having lot of issues on moving our server from TrinityCoreLegacy to this amazing core due to remove of the Authserver. 

Bnetserver expects some hacks in the client in order to work. We have many players whose client are cannot be connection patched due to old private server patches and some doesn't even want to modify their client apart from realmlist, since they also play on other 4.3.4 server.

**Current behaviour:**

We have only Bnetserver.

**Expected behaviour:**

Authserver should be an optional solution.

**TC rev. hash/commit:** 

TrinityCore rev. 1dd44ab 2020-07-09 22:01:32 +0200 (master branch) (Win64, Release, Static) (worldserver-daemon)

**TDB version:**  TDB 434.20051

**Operating system:** Windows 10

**Comment by funjoker** [comment]
Normal auth server requires those "hacks" too.
The bnet server patcher changes far less things in client than the oldschool patcher.

**Comment by miirak** [comment]
> Normal auth server requires those "hacks" too.
> The bnet server patcher changes far less things in client than the oldschool patcher.

Then this is interesting because in my memory of the past you could just switch between servers without the importance of downloading local battle.net auth module staff.

**Comment by Ovahlord** [comment]
You don't get it. ALL private servers use a hacked exe file. Every. Single. One. Of. Them. The difference between the old login method and the current one is, that the old hacking was disabling the 2nd connection and was not supporting bnet at all. We do that. The modules are for the 2nd connection and the connection patcher is patching the needed part to get that one working for pservers.

The reason why many people struggle with that setup is:
1. They use a already hacked exe which has killed the 2nd connection that we need (aka. a modified client)
2. The modules are necessary to establish the 2nd connection. the trinity master branch does that as well, except that they hack the memory during runtime via client launcher instead of a patcher.

Even if the authserver would be restored, you still wont be able to use your average hacked client because we still would have the 2nd. connection which is a requirement. A proper player friendly approach would be creating a client launcher like master has that patches the things during runtime and reverts the old private server hacks if necessary.

**Comment by miirak** [comment]
@Ovahlord Ahh I didn't know that, thank you for these I've never heard them before, but wait a minute I remember using blizzard launcher installed WoTLK client for a private server back in the days, that cannot contain modified exe.  Or WoTLK exe didn't contain the 2nd connection (bnet)?

**Comment by Ovahlord** [comment]
WotLK was not using any patch at all. It started with 4.x when Blizz fully switched over to battle.net and implemented a 2nd session. That's one of the reasons why cata was unplayable on pservers for a very long time back then when it launched

**Comment by miirak** [comment]
Ahh I remember now when cata came out I had to download an exe for the first time, I was like 11 years old back then and was calling that exe "crack" lol. I am gonna close the issue, thank you for your time!
