### ISSUE TITLE
Pet health regeneration after killing mobs

### ISSUE THREAD

**Issue by TranceAccount** [The-Cataclysm-Preservation-Project/TrinityCore#161]
**Description:**

It appears that pets do not regenerate health after fighting mobs. I also tried the .dam command on a pet of a freshly created hunter and relogged hunter, which has not killed any mobs yet, and the pet just regenerates health.

**Current behaviour:**

Pets do not regenerate health after fighting with mobs.

**Expected behaviour:**

After pet participated in killing a mob and when out of combat, pet should start to regenerate health.

**Steps to reproduce the problem:**

1. Create a new hunter char.
2. Enter world and skip intro video.
3. Target pet and do .dam 10. Observe that it regenerates health.
4. Kill a mob and make sure pet participates in the fight. (Does not necessarily need to take damage, see next step)
5. .dam 10 on pet again, and observe that it does not regenerate health.
6. Relog and observe pet is full health again.

**TC rev. hash/commit:** 

TrinityCore rev. e57ec6597329 2020-07-29 23:03:02 +0200 (master branch) (Win64, RelWithDebInfo, Static)

**TDB version:**  

TDB 434.20051

**Operating system:** 

Windows 10 Home

**Comment by Ovahlord** [comment]
Though it was actually working (it was just REALLY low) it's now normalized and works just fine

**Comment by sxf1749** [comment]
Description:

 in TrinityCore rev. bc0703e55c89 2021-03-11 19:53:48 +0100 (master branch) (Unix, RelWithDebInfo, Static
Pets do not regenerate health after fighting with mobs, maybe just a visual bug cos when i relogin pet's health is full

Current behaviour:

Pets do not regenerate health after fighting with mobs.

Expected behaviour:

After pet participated in killing a mob and when out of combat, pet should start to regenerate health.

Steps to reproduce the problem:

maybe just a visual bug, cos pet's health is full when i relogin 

TC rev. hash/commit:

 TrinityCore rev. bc0703e55c89 2021-03-11 19:53:48 +0100 (master branch) (Unix, RelWithDebInfo, Static

TDB version:

TDB 434.20051

Operating system:

ubuntu20
