### ISSUE TITLE
Unit_class 4 adds no energy bar on creatures

### ISSUE THREAD

**Issue by Nyr97** [The-Cataclysm-Preservation-Project/TrinityCore#233]
**Description:** Units set to unit_class 4 (energy user) in creature_template have no energy to use. Their power bar is empty. Neither do they regenerate energy while having UNIT_FLAG2_REGENERATE_POWER.

**Current behaviour:** Units set to unit_class 4 (energy user) in creature_template have no energy to use.

**Expected behaviour:** Units set to unit_class 4 should have an energy bar of 100 points.

**Steps to reproduce the problem:**

1. On creature_template, add 4 on unit_class on any creature.
2. Summon the creature in game.
3. Watch his template to notice the bug.

**TDB version:** TDB_full_world_434.20091_2020_09_22.sql

**Operating system:** Windows 10.

**Comment by Ovahlord** [comment]
unit class rogue does not mean that the unit is suposed to use energy. energy is determined either by a vehicle id or by setting the power type to energy by script.

**Comment by Nyr97** [comment]
Unit_class is supposed to change the creature's power bar on demand. It makes zero sense to only influenciate health when setting option 2 or 8 converts its power bar into mana. In Vanilla, in fact, most world npcs were scripted through SmartAI, which couldn't, and can't up to this date, change a creature's power bar.

How is it that many branches of TrinityCore I've used and other cores have this functionality through DB and not only core-based?

**Comment by Ovahlord** [comment]
because these said branches hacked shit out of them. unit_class_rogue is suposed to be exactly as unit_class_warrior except that units with that class have fewer health than warrior units. That's it. It does not mean that this creature is an exact replication of a rogue player with energy.

Creatures that use energy are mostly scripted so the power type handling belongs in there and most post wotlk creatures with a power bar use a vehicleId to setup the power type and power amount

**Comment by Nyr97** [comment]
Update to this: this assumption was wrong as I expected. UNIT_CLASS_ROGUE does have a role in setting a creature's power as energy. More info on the matter is on master branch.

**Comment by Ovahlord** [comment]
That's a master only feature.  Power types do not have flags or default powers in 4.x
